### ISSUE TITLE
数据集的问题

### ISSUE THREAD

**Issue by zyxdSTU** [circlePi/Pretraining-Yourself-Bert-From-Scratch#2]
大佬你好，认真看了你的代码。清晰明了，棒。
我想问一下数据集的问题
达观给了一个数据集， 训练集，和测试集的比例多少合适
显存10个G的显卡，够用吗？不够用的话，bert应该调整那些参数？
还有在实际应用过程中，输入的句子是《CLS》x1,x2...xn<SEP>还是可以x1,x2,...xn

**Comment by circlePi** [comment]
1. 达观的数据集去重后大概85w左右，建议训练集：验证集=84：1
2. 10G显卡跑BERT base够用了，不过batch_size可能要设的小一点，比如8，可以在lm_smallBert/pretrain_args.py里修改。另外，你可以修改bert_config.json里对模型层数进行修改，减小模型层数也可以降低显存。
3. 实际finetuning时， 句子输入是[CLS] text_a [SEP]. 引导符建议加上

**Comment by circlePi** [comment]
另一个降低显存使用的办法是使用 fp16，可以在pretrain_args.py里修改下配置 fp16=True. 前提是你的卡支持fp16, 并且安装了 apex。使用fp16，训练速度大概提升一倍，显存使用大概降低一半

**Comment by zyxdSTU** [comment]
> 另一个降低显存使用的办法是使用 fp16，可以在pretrain_args.py里修改下配置 fp16=True. 前提是你的卡支持fp16, 并且安装了 apex。使用fp16，训练速度大概提升一倍，显存使用大概降低一半
               `if nb_tr_steps > 0 and nb_tr_steps % 100 == 0:`
 `if nb_tr_steps > 0 and nb_tr_steps % 2000 == 0:`
这段代码是不是错了啊， 两个if应该是并列的吗？ 可能作者复制粘贴的时候出现问题。
还有问一下作者训练达观数据训练了多久， 方便留个QQ吗？ 大佬

**Comment by circlePi** [comment]
> > 另一个降低显存使用的办法是使用 fp16，可以在pretrain_args.py里修改下配置 fp16=True. 前提是你的卡支持fp16, 并且安装了 apex。使用fp16，训练速度大概提升一倍，显存使用大概降低一半
> > `if nb_tr_steps > 0 and nb_tr_steps % 100 == 0:`
> > `if nb_tr_steps > 0 and nb_tr_steps % 2000 == 0:`
> > 这段代码是不是错了啊， 两个if应该是并列的吗？ 可能作者复制粘贴的时候出现问题。
> > 还有问一下作者训练达观数据训练了多久， 方便留个QQ吗？ 大佬

这段代码是对的，每100步打印训练损失，每2000步验证。

**Comment by Crescentz** [comment]
请问你训练用时多久，效果好么
